sudo: false
language: python
python:
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: 'matsurihime'
  password:
    secure: 'rFYXxG8muqG+jCBiDpDAkEI8Ody/qXsXW9jGE8frNc3ZtMx1W14UIJ+zHXbuhJz4M7aJRWtP537ToYWi8gOsPby3nwpLCZY0llrB70HYLW3MTCRDhHi7sJuK1OWfqCDXBEGM1SMGWoB1tAojMz7NJD402Ag8O14yBlrBWO21gbsj7b7zC/xxVD3d1tR0UlOfRy9FhTJvbRPYagRAfzHb9Bu5h3Dnz6JNsrHDg3PQFFc+xzpcIpjpTsaZ+VPEqhPYMpAK4ZHRs1ISmeza6Mb8GXNvMG3tnVZtNzIEJCcNfqgP22ZizF/AaAQEXTo6ajsYN9wM2fOSoPbYRDfv6vO2V9iVeLjVfbpU4YosQVPQSSUtVfulJtaIvkkMWWp4DZF2aKdrmqe610V8rOywa8Q61qGC4p01R2iXWtuPpwYEcgiMoe2nSB3nwuIksO22TDyiMxZ2tgVljv95kBmsL7on1AP7DcyaiT10algQSMdQ5OGB+3vuApLGuIrhKX9mWoLvdUx45k286wcqSJSOFiCum0jjPeU1hylFknzVdquMjj2KRUMXNCiAoLxNWtccW5E2lwNHlUr0NJ+bviHW+AW8Wblx+aTOKq7HlxbgH+fBdfzDI3SNqxXMNuyEvFovuH+kDla+GF8VsyoIxln2ejqR/mZa+KLX/GCorb3T/ma5YuY='
  on:
    tags: true
